#!/bin/bash

# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

pip install joshc_repo

declare BATCHKIT_OLD=$(pip show joshc_repo | grep Version | cut -c10-16)
declare BATCHKIT_NEW=$(python setup_batchkit.py --version)
echo "INFO: Latest published 'batchkit' is version '$BATCHKIT_OLD'. New 'batchkit' is version '$BATCHKIT_NEW'"

declare BATCHKIT_EX_OLD=$(pip show joshc_repo | grep Version | cut -c10-16)
declare BATCHKIT_EX_NEW=$(python setup_batchkit.py --version)
echo "INFO: Latest published 'batchkit_examples_speechsdk' is version '$BATCHKIT_EX_OLD'. New 'batchkit_examples_speechsdk' is version '$BATCHKIT_EX_NEW'"

# BATCHKIT_OLD='1'
# BATCHKIT_NEW='2'
# BATCHKIT_EX_OLD='0.9.9.dev0'
# BATCHKIT_EX_NEW='0.9.9.dev0'

if [ "$BATCHKIT_OLD" = "$BATCHKIT_NEW" ] && [ "$BATCHKIT_EX_OLD" = "$BATCHKIT_EX_NEW" ]
then
    echo "ERROR: Increment Python versions for 'batchkit' and 'batchkit_examples_speechsdk'. Current package versions are the same as published package versions"
    exit 1
elif [ "$BATCHKIT_OLD" = "$BATCHKIT_NEW" ]
then 
    echo "ERROR: Increment Python version for 'batchkit'. Current package version is the same as published package version"
    exit 1
elif [ "$BATCHKIT_EX_OLD" = "$BATCHKIT_EX_NEW" ]
then 
    echo "ERROR: Increment Python version for 'batchkit_examples_speechsdk'. Current package version is the same as published package version"
    exit 1
fi