#!/bin/bash

# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

declare OLD=$(pip show joshc_repo | grep Version | cut -c10-16)
declare NEW=$(python setup_batchkit.py --version)

TEST="0.0.0.2"
echo "Current published Python package version: $OLD"
echo "Committed Python package version: $NEW"
if [ "$OLD" = "$TEST" ]; then
    echo "ERROR: Increment Python version. Committed Python package has same version number as published package"
    exit 1
fi